//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignMode.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DesignMode.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Action.
        /// </summary>
        internal static string ActionDesign {
            get {
                return ResourceManager.GetString("ActionDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new action..
        /// </summary>
        internal static string ActionDesignDesc {
            get {
                return ResourceManager.GetString("ActionDesignDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Composite.
        /// </summary>
        internal static string CompositeDesign {
            get {
                return ResourceManager.GetString("CompositeDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new sequence, selector or parallel..
        /// </summary>
        internal static string CompositeDesignDesc {
            get {
                return ResourceManager.GetString("CompositeDesignDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Condition.
        /// </summary>
        internal static string ConditionDesign {
            get {
                return ResourceManager.GetString("ConditionDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new condition..
        /// </summary>
        internal static string ConditionDesignDesc {
            get {
                return ResourceManager.GetString("ConditionDesignDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Decorator.
        /// </summary>
        internal static string DecoratorDesign {
            get {
                return ResourceManager.GetString("DecoratorDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new decorator..
        /// </summary>
        internal static string DecoratorDesignDesc {
            get {
                return ResourceManager.GetString("DecoratorDesignDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        internal static string DesignLabel {
            get {
                return ResourceManager.GetString("DesignLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The label shown on the node..
        /// </summary>
        internal static string DesignLabelDesc {
            get {
                return ResourceManager.GetString("DesignLabelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Event.
        /// </summary>
        internal static string EventDesign {
            get {
                return ResourceManager.GetString("EventDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new event..
        /// </summary>
        internal static string EventDesignDesc {
            get {
                return ResourceManager.GetString("EventDesignDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Impulse.
        /// </summary>
        internal static string ImpulseDesign {
            get {
                return ResourceManager.GetString("ImpulseDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new impulse..
        /// </summary>
        internal static string ImpulseDesignDesc {
            get {
                return ResourceManager.GetString("ImpulseDesignDesc", resourceCulture);
            }
        }
    }
}
